### ISSUE TITLE
Fix overflow of addresses on mobile

### ISSUE THREAD

**Issue by samromaincamel** [turingmachinenetwork/turingmachinenetwork.github.io#1]
![2021-04-17 10 43 41](https://user-images.githubusercontent.com/82704287/115108716-d9d61300-9f69-11eb-8704-5a60dfa517b9.jpg)

**Comment by janbacnn** [comment]
We are working on it.

**Comment by janbacnn** [comment]
https://github.com/turingmachinenetwork/turingmachinenetwork.github.io/commit/43d0c0930e2f2a7f711af955264b0de6655c942f
