### ISSUE TITLE
Add name metadata to website

### ISSUE THREAD

**Issue by samromaincamel** [turingmachinenetwork/turingmachinenetwork.github.io#2]
![Screenshot 2021-04-17 at 10 46 58](https://user-images.githubusercontent.com/82704287/115108783-3d604080-9f6a-11eb-971c-957089caf6e7.png)

**Comment by janbacnn** [comment]
https://github.com/turingmachinenetwork/turingmachinenetwork.github.io/commit/43d0c0930e2f2a7f711af955264b0de6655c942f
